insert into  t_question ( 
content,
question_classify_id,
question_type,
difficulty_level,
enable_status,
answer_thought,
update_time,
update_by,
create_time,
create_by,
teacher_id,
data_flag,
valid_flag)
  values(
#{data.content},
#{data.questionClassifyId},
#{data.questionType},
#{data.difficultyLevel},
#{data.enableStatus},
#{data.answerThought},
now(),
#{data.updateBy},
now(),
#{data.createBy},
#{data.createBy},
1,
0
)